config/routes.rb
Rails.application.routes.draw do
  resources :workouts do
  	resources :gym_classes
  end
  root 'workouts#index'
end

app/models/workout.rb
class Workout < ActiveRecord::Base
	has_many :gym_classes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
	before_action :find_workout, only: [:show, :edit, :update, :destroy]

	def index
		@workouts = Workout.all.order("created_at DESC")
	end

	def show

	end

	def new
		@workout = Workout.new
	end

	def create
		@workout = Workout.new(workout_params)
		if @workout.save
			redirect_to @workout
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @workout.update(workout_params)
			redirect_to @workout
		else
			render 'edit'
		end
	end

	def destroy
		@workout.destroy
		redirect_to root_path
	end

	private

	def workout_params
		params.require(:workout).permit(:date, :workout, :mood, :length)
	end

	def find_workout
		@workout = Workout.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Workout Log Application</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
<body>
	<nav class="navbar navbar-default">	
		<div class="container">	
			<%= link_to "Workout Log", root_path %></br>
			<%= link_to "New Workout", new_workout_path %>
		</div><!-- /.container-fluid -->
	</nav>	


	<div class="container">	
	<%= yield %>
	</div>

</body>
</html>	

app/views/workouts/_form.html.erb
<%= simple_form_for(@workout, html: {class: 'form-horizonal'}) do |f| %>
  <%= f.input :date, label: "Date" %>
  <%= f.input :workout, label: "What kind of workout?", input_html: { class: "form-control" } %>
  <%= f.input :mood, label: "How are you feeling?", input_html: { class: "form-control" } %>
  <%= f.input :length, label: "How long was the workout?", input_html: { class: "form-control" } %>
  <br/>
  <%= f.button :submit %>
<% end %>  

app/views/workouts/edit.html.erb
<h1>Edit Workout</h1>
<%= render 'form' %>
<%= link_to "Cancel", root_path %>

app/views/workouts/index.html.erb
<h1> All Workouts </h1>

<% @workouts.each do |workout| %>
<%= link_to workout.date.strftime("%A, %B %d"), workout %></br>
<%= workout.workout %></br>
<% end %>

app/views/workouts/new.html.erb
<h1>New Workout</h1>
<%= render 'form' %>
<%= link_to "Cancel", root_path %>

app/views/workouts/show.html.erb
<%= @workout.date %></br>
<%= @workout.workout %></br>
<%= @workout.mood %></br>
<%= @workout.length %></br>

<h3>Add Workout</h3>
	<%= link_to "New Workout", new_workout_path %>

<h3>Add a gym class</h3>
<%= render "gym_classes/form" %>

<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_workout_path(@workout) %>
<%= link_to "Delete", workout_path(@workout), method: :delete, data: { confirm: "Are you sure?" } %>